### ISSUE TITLE
Add global rate limit

### ISSUE THREAD

**Issue by martinthomson** [ice-wg/rfc5245bis#13]

**Comment by cdh4u** [comment]
Annex B.1 also contain some text regarding the rate.

E.g.

"The definition of a "reasonable" rate is that STUN should not use
 more bandwidth than the RTP itself will use, once media starts
 flowing."

I guess we should discuss whether: 1) We need to remove/modify that text 2) Whether B.1 is the place where we should talk about the global rate limit.

**Comment by pthatcherg** [comment]
I'll own this issue because I'm driving discussion on the list around the transport guys' proposal for "MaxPackets+HTO+pacing".

**Comment by pthatcherg** [comment]
Hopefully fixed by https://github.com/ice-wg/rfc5245bis/pull/19
