### ISSUE TITLE
Possible contradiction in freezing algorithm in section 5.8 and sections 5.7.4 and 7

### ISSUE THREAD

**Issue by pthatcherg** [ice-wg/rfc5245bis#3]
We seem to have a contradiction in the (un)freezing algorithm (thanks to Justin Uberti and Emil Ivov for finding it). Section 5.8 implies that unfreezing one candidate pair unfreezes a whole list.  The other sections imply that you just unfreeze that pair.  

Emil's proposed resolution is to use change section 5.8 to make it clear we only unfreeze one candidate pair.

Link to the email discussion:

https://www.ietf.org/mail-archive/web/ice/current/msg00220.html

**Comment by cdh4u** [comment]
There is no section 5.8 in 5245bis, and the other referenced sections don't exist either. I assume they refer to sections in RFC 5245, but it would be good to "update" the e-mail to point to 5245bis sections.

**Comment by pthatcherg** [comment]
As pointed out by Peter Saint-Andre, here is how the sections were moved:

5245    ===>    5245bis

2.4             2.4
5.7.4           5.1.3.4
5.8             5.1.4
7.1.3.2.3       6.1.3.2.3

**Comment by pthatcherg** [comment]
We got it all resolved at IETF 96.
