### ISSUE TITLE
What is the scope of uniqueness of priority? It's ambiguous.

### ISSUE THREAD

**Issue by pthatcherg** [ice-wg/rfc5245bis#39]
The text just says it needs to be unique.  It doesn't unique within what scope.  I think it should be unique within the scope of a single component of a single media stream within a single session.  

But whatever we decide, it should be clear in the spec.  Right now, it's not.

**Comment by akeranen** [comment]
Section 4.1.2 says "Each candidate for a media stream MUST have a unique priority"
(https://tools.ietf.org/html/draft-ietf-ice-rfc5245bis-10#section-4.1.2)

I think I've always read that as in "unique within a media stream", but indeed it can also be interpreted as "candidates in general" since all are part of some media stream. But I think media stream is the right scope. Uniqueness across components is taken care of by the "Component ID" part of the formula. 

I'd suggest changing that text into "Each candidate for a media stream MUST have a unique priority in the scope of a media stream."

**Comment by cdh4u** [comment]
I agree that we need to define the scope of the uniqueness - it's something the IESG reviewers (and sometimes also the Gen-ART reviewers) ask about if unclear.

**Comment by pthatcherg** [comment]
The problem with relying on the formula is that it's only SHOULD strength.  But the uniqueness is MUST strength.

Which means that an implementation is free to use a different formula, but it must preserve the uniqueness, so the MUST-level text needs to clarify the uniqueness, not the SHOULD-level text.  I like Ari's idea of adding to the MUST-level text to make it clear and not rely on the formula.

So, two questions about that:

1.  Do we need to specify that it's within the scope of a single session (ICE restart)?  I think it's what is currently assumed by the text (else ICE restarts would have to keep track of the priorities of past generations, which it doesn't say needs to be done), but I think it would be nice to be explicit.

2.  Do we need to have uniqueness across components?  I don't really see any reason for it, but maybe I'm missing something.  On the other hand, it doesn't seem very difficult to keep them unique across components.  So I don't think it matters too much.

**Comment by cdh4u** [comment]
Related to this, note that the local preference value must also be unique - without any description of the scope of the uniqueness.

Regarding your questions:

1) I assume "scope of an ICE session" means that the priority value is unique among all media streams associated with that session?

2) Not sure I understand. If all candidates have unique priority values, that means the components will have unique priority values too.

**Comment by pthatcherg** [comment]
Regarding "scope of an ICE session", what I meant is that if you have an ICE restart, you can re-use values from the previous round of gathering.  You don't have to remember values from the past and avoid reusing them.  I did *not* mean that a value has to be unique across all media streams (that would be crazy).

Regarding candidates having unique priorities across components, what I mean is: is it OK for two candidates to be for the same stream but different components and have the same priority?  I don't see why not.  But again, I don't see it as  big restriction to say that they have must be different.

**Comment by pthatcherg** [comment]
I think this is still not resolved, and Christer pointed out that in IESG review they might ask about this.

**Comment by cdh4u** [comment]
Isn't this covered with the modified text in section 5.2?

"In addition, each candidate MUST be assigned a unique priority amongst all candidates for the same data stream."

**Comment by pthatcherg** [comment]
"For the same data stream" is great!  I didn't realize that was in there.  In that case, I think we can close the issue.
