### ISSUE TITLE
Problems in ICE restart behavior

### ISSUE THREAD

**Issue by pthatcherg** [ice-wg/rfc5245bis#4]
Some problems with the ICE restart behavior were recently found by Taylor Brandstetter, most significantly that ICE restarts currently must change the ICE role and tiebreaker, but that if the role/tiebreaker of one media stream is changed, then it must change for all media streams, which means that if only one media stream is reset but not the others, then the role of a live media stream would change suddenly, which could lead to unnecessary role conflicts.

The proposed resolution on the list is to not change the role/tiebreaker on ICE restart, and only rely on role conflicts and ICE full->lite changes for role changes.

Mailing list thread:

https://www.ietf.org/mail-archive/web/ice/current/msg00208.html

**Comment by cdh4u** [comment]
One thing to keep in mind: any ICE agent can trigger the restart, i.e. be the "initiating agent". It needs to be clear that in this case the initiating-agent-which-started-the-ICE-processing-MUST-take-the-controlling-role rule does not apply during an ICE restart.

**Comment by taylor-b** [comment]
I agree. That's exactly the situation that lead me to re-examine this text.

**Comment by pthatcherg** [comment]
I believe this was resolved by merging PR 12: https://github.com/ice-wg/rfc5245bis/commit/614130a727da042fc0349bbb0f101e1d040b9b64
