### ISSUE TITLE
Update "changes from 5245" section

### ISSUE THREAD

**Issue by pthatcherg** [ice-wg/rfc5245bis#40]

**Comment by pthatcherg** [comment]
The changes section looks very small compared to how many changes we've made, so it definitely needs updating.  Now we need to decide whether we have to update it before or after requesting publication.

**Comment by cdh4u** [comment]
Yes - we just have to remember everything :) However, I don't think we should go into details: the major changes (that I can think of when writing this) are removal of regular/aggressive nomination, and the changes related to "Emil's table".
