### ISSUE TITLE
Update candidate removal (when there are too many) to be evenly distributed

### ISSUE THREAD

**Issue by pthatcherg** [ice-wg/rfc5245bis#41]
To prevent one check list from starving.

**Comment by cdh4u** [comment]
This was discussed (and, as far as I am concerned, agreed) on the list 1st June. But, it's good to have a reminder :)

**Comment by pthatcherg** [comment]
This one has not been addressed as far as I can tell.  Now we get to decided if it's important enough or not to do something about :)

**Comment by cdh4u** [comment]
I had a look at this, but for some reason it never got implemented. I think it should be an easy fix.
